### ISSUE TITLE
Ternary operator description inconsistent

### ISSUE THREAD

**Issue by karollewandowski** [adobe/htl-spec#72]
The ternary operator is defined as part of expression node:
```
exprNode = orBinaryOp , '?' , orBinaryOp , ws , ':' , ws , orBinaryOp
...
```

In description there is:
> `${varChoice ? varOne : varTwo}     <!--/* 5. Conditional (ternary) (note that the ? and : separators must be surrounded by a space) */-->`

If `?` should be surrounded by whitespaces then production should look like:
```
exprNode = orBinaryOp , ws , '?' , ws , orBinaryOp , ws , ':' , ws , orBinaryOp
...
```
Which option is correct?

**Comment by raducotescu** [comment]
The only reason for which ":" should be surrounded by whitespace is that ":" is allowed in identifier names. Take the following expression as an example:

```
${true? properties.jcr:title:'My Title'}
```

This would result in an error, since the last ":" would be considered part of the identifier, instead of a part of the ternary operator. However, the spaces around "?" don't really matter. Maybe we should enhance the grammar to specify that those spaces are optional:

```
exprNode = orBinaryOp , [ws, ] '?' [ws, ] , orBinaryOp , ws , ':' , ws , orBinaryOp | orBinaryOp ;
```

**Comment by karollewandowski** [comment]
Reason for `WS` around `:` was clear for me, the only question was about inconsistencies for `?`. Indeed spaces around `?` can be optional. I just want to know how to implement the parser in IntelliJ plugin I'm working on to have it fully spec compliant.
Regarding:
>Maybe we should enhance the grammar to specify that those spaces are optional:
>```
>exprNode = orBinaryOp , [ws, ] '?' [ws, ] , orBinaryOp , ws , ':' , ws , orBinaryOp | orBinaryOp ;
>```
I think it is redundant as `,` (comma) is produced to:
```
, = {ws} ;
```
(zero or more whitespaces).

BTW, maybe it would be good to consider changing grammar notation to make it closer to ANTLR (eg. `()*` instead of `{}`)? I think this one is pretty hard to read and using common expressions like mentioned `()*` or `()?` would more familiar for people. If you agree I have it as a result of analyzing grammars (spec's and Sling's) for my side project.
