### ISSUE TITLE
Unwrap block description issue

### ISSUE THREAD

**Issue by karollewandowski** [adobe/htl-spec#74]
The `data-sly-unwrap` block says that element is never shown. 

> 2.2.11. Unwrap
> `data-sly-unwrap`:
> 
> Unwraps the element.
> **Element: never shown.**
> Content of element: always shown.
> Attribute value: optional; an expression evaluated as `Boolean`; defaults to `true` if the value is omitted.
> Attribute identifier: optional; identifier name to access the result of the test.
> Scope: The identifier set by the `data-sly-unwrap` block element is global to the script and can be used anywhere after its declaration.

Element visibility depends on the attribute value, so it should rather say:
> 2.2.11. Unwrap
> `data-sly-unwrap`:
> 
> Unwraps the element.
> Element: shown if expression evaluates to `false`.
> Content of element: always shown.
> Attribute value: optional; an expression evaluated as `Boolean`; defaults to `true` if the value is omitted.
> Attribute identifier: optional; identifier name to access the result of the test.
> Scope: The identifier set by the `data-sly-unwrap` block element is global to the script and can be used anywhere after its declaration.

I'm not sure if it should say "`false`" or "falsy value" as empty array and `0` also renders element (at least in Sling implementation I'm using - from AEM 6.1). Strange is that empty string is not "falsy".

**Comment by raducotescu** [comment]
Fixed in 08661ca.
