### ISSUE TITLE
i18n source missing from spec

### ISSUE THREAD

**Issue by santiagozky** [adobe/htl-spec#79]
The i18n option for strings support passing a 'source' parameter to influence where the locale is taken from (resource or user), but this seems missing from the spec:

https://helpx.adobe.com/experience-manager/htl/using/expression-language.html#Internationalization
https://issues.apache.org/jira/browse/SLING-6983

could you please add it?

**Comment by raducotescu** [comment]
@santiagozky, the `source` option is specific to Apache Sling / Adobe Experience Manager since HTL doesn't have the concept of Page / User.
