### ISSUE TITLE
Need syntax to access Referer in Request Header using HTL (SlightlyJS)

### ISSUE THREAD

**Issue by grbbabu** [adobe/htl-spec#83]
Hi,
Could you please provide me the syntax to access Referer in Request Header using HTL (SlightlyJS) only?
Thanks in advance.
Ramesh babu

**Comment by raducotescu** [comment]
This is not a question pertaining to the specification. However, something along these lines should work:
```javascript
"use strict";
use(function () {
    var referer = request.getHeader('Referer');
    if (referer !== null) {
        // code here
    }
});
```
