### ISSUE TITLE
list and repeat should allow for `len` instead of `end`

### ISSUE THREAD

**Issue by tripodsan** [adobe/htl-spec#84]
In case the collection is large, potentially infinite (iterator) or its size is not known, it would be more practical to use `len` instead of `end`.

**Comment by raducotescu** [comment]
@tripodsan, in this case `end` has nothing to do with the collection's size, but rather at which element to stop the iteration:
> `end` - iteration ends at the item located at the specified index (inclusive)

If you want to iterate over the whole content don't supply the `end` option:
```
<ul data-sly-list="${myCollection @ start=2}">
    <li>${item}</li>
</ul>

<p data-sly-repeat="${myCollection @ start=2}">${item}</p>
```

**Comment by tripodsan** [comment]
> but rather at which element to stop the iteration:

element of the _stepped_ list or the original ?

#### stupid example:
Assume I have an iterator that generates odd numbers: `1, 3, 5, 7, 9, 11, 13, ...`
I want to display `5, 9, 13`, so I need to specify: `start=2, step=2, end=6` right?

it would be easier to specify `len=3`.

**Comment by raducotescu** [comment]
> element of the stepped list or the original ?
Element of the list provided in the expression (so original, if you want to qualify it this way). And your example is correct.

When we defined these expression options we wanted to be close to the JSP specification for the `c:forEach` [0] standard tag.

Adding a `len` option could suggest that implementations should create a sub-list, when what you want is to control how many iterations to do, based on the `start` and `step` values.

[0] - https://download.oracle.com/otn-pub/jcp/jstl-1.1-mr2-spec-oth-JSpec/jstl-1_1-mr2-spec.pdf

**Comment by tripodsan** [comment]
ok.
